<?php
// Autogenerated extension filesystems
// This config is merged with config/filesystems.php

return [
  'disks' => [
    /* blueprint/disks *//* RustserverwiperStart */ 'blueprint:rustserverwiper' => [ 'driver' => 'local', 'root' => storage_path('extensions/rustserverwiper'), 'url' => env('APP_URL') . '/fs/extensions/rustserverwiper', 'visibility' => 'public', 'throw' => false, ], 'blueprint_private:rustserverwiper' => [ 'driver' => 'local', 'root' => storage_path('.extensions/rustserverwiper'), 'throw' => false, ], /* RustserverwiperEnd */
  ],
];
